#!/bin/bash
set -euo pipefail

cleanup() {
	jobs -p | xargs kill
}

trap cleanup EXIT

echo "Starting moq-api"
PORT=4420 /home/gergo/szakdolgozat/moq-rs-telemetry/dev/api &

echo "Starting spine"
for ((i = 1; i <= 1; i++)); do
	export PORT="$((4420 + i))"
	export API="http://localhost:4420"
	export NODE="https://localhost:${PORT}"
	/home/gergo/szakdolgozat/moq-rs-telemetry/dev/relay &
done

echo "Starting leaf"
for ((i = 2; i <= 2; i++)); do
	export PORT="$((4420 + i))"
	export API="http://localhost:4420"
	export NODE="https://localhost:${PORT}"
	export ARGS="--next-relays https://localhost:4421"
	/home/gergo/szakdolgozat/moq-rs-telemetry/dev/relay &
done

echo "Starting leaf"
for ((i = 3; i <= 3; i++)); do
	export PORT="$((4420 + i))"
	export API="http://localhost:4420"
	export NODE="https://localhost:${PORT}"
	export ARGS="--next-relays https://localhost:4422"
	/home/gergo/szakdolgozat/moq-rs-telemetry/dev/relay &
doneí

while true; do
	sleep 100
done
